project:
  type: website

website:
  title: "Data Science and Applied Topology Seminar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - archive.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

execute:
  freeze: auto

